Update TraceWriter.cs
This class shoud be public, or provide another method to log non-fatal exceptions.

This change the call stack from:

Package: dies.mobile.droid
Version: 17
Android: 4.2.2
Manufacturer: Genymotion
Model: 4.2.2 - API 17 - HDPI
Date: 4/20/2016 12:35:38 AM

System.Net.WebException: Error: TrustFailure (The authentication or decryption has failed.)
	at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult_asyncResult.args:1337)
	at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic(IAsyncResult_iar__System.Func`2_endFunction__System.Action`1_endAction__System.Threading.Tasks.Task`1_promise__Boolean_requiresSynchronization.args:1337)
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult(.args:1337)
	at System.Net.Http.HttpClientHandler+<SendAsync>c__async0.MoveNext(.args:1337)
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult(.args:1337)
	at System.Net.Http.HttpClient+<SendAsyncWorker>c__async0.MoveNext(.args:1337)
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult(.args:1337)
	at dies.mobile.droid.Dies.Mobile.Core.Loaders.Loader+<LoadHtmlNode>c__async2.MoveNext(.args:1337)
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult(.args:1337)
	at dies.mobile.droid.Dies.Mobile.Core.Loaders.ProjudiLoader+<LoadProcessoAsync>c__async0.MoveNext(.args:1337)
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task_task.args:1337)
	at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult(.args:1337)
	at dies.mobile.droid.Dies.Mobile.Core.AddTrialByNumberViewModel+<AddTrialByNumber>c__async0.MoveNext(.args:1337)

To:

System.Net.WebException: Error: TrustFailure (The authentication or decryption has failed.)
	at System.Net.HttpWebRequest.EndGetResponse(HttpWebRequest.cs:1005)
	at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic(FutureFactory.cs:550)
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(exceptionservicescommon.cs:143)
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(TaskAwaiter.cs:187)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(TaskAwaiter.cs:156)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(TaskAwaiter.cs:128)
	at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult(TaskAwaiter.cs:357)
	at dies.mobile.droid.MakerPlanet.Mobile.Dies.Loaders.HtmlDownloader+<GetStreamAsync>c__async3.MoveNext(HtmlDownloader.cs:82)
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(exceptionservicescommon.cs:143)
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(TaskAwaiter.cs:187)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(TaskAwaiter.cs:156)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(TaskAwaiter.cs:128)
	at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult(TaskAwaiter.cs:357)
	at dies.mobile.droid.MakerPlanet.Mobile.Dies.Loaders.HtmlDownloader+<GetHtmlNodeAsync>c__async1.MoveNext(HtmlDownloader.cs:30)
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(exceptionservicescommon.cs:143)
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(TaskAwaiter.cs:187)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(TaskAwaiter.cs:156)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(TaskAwaiter.cs:128)
	at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult(TaskAwaiter.cs:357)
	at dies.mobile.droid.MakerPlanet.Mobile.Dies.Loaders.HtmlDownloader+<GetHtmlNodeAsync>c__async0.MoveNext(HtmlDownloader.cs:24)
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(exceptionservicescommon.cs:143)
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(TaskAwaiter.cs:187)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(TaskAwaiter.cs:156)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(TaskAwaiter.cs:128)
	at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult(TaskAwaiter.cs:357)
	at dies.mobile.droid.Dies.Mobile.Core.Loaders.PjeLoader+<LoadProcessoAsync>c__async0.MoveNext(PjeLoader.cs:44)
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(exceptionservicescommon.cs:143)
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(TaskAwaiter.cs:187)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(TaskAwaiter.cs:156)
	at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(TaskAwaiter.cs:128)
	at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult(TaskAwaiter.cs:357)
	at dies.mobile.droid.Dies.Mobile.Core.AddTrialByNumberViewModel+<AddTrialByNumber>c__async0.MoveNext(AddTrialByNumberViewModel.cs:91)

Which is correct.